const ApiCategoryShower= 
//Femme Vetements
[
    {
    id:1,
    category:"femme",
    sousCategory:"vetements",
    products:[
        {
            id : 528773, 
            img : "https://www.awalebiz.com/images/detailed/15/Kiba_Tima_02.jpg", 
            title : "Ensemble Boubou",
            desc : "Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.",
            price : "100",
            id_cat:1,
        },
        {
            id : 179449, 
            img : "https://www.awalebiz.com/images/detailed/15/Kiba_Fina_02.jpg", 
            title : "Ensemble Boubou",
            desc :"Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.            ",
            price : "100", 
            id_cat:1,
        },
        {
            id : 512934, 
            img : "https://www.awalebiz.com/images/detailed/15/Makiba_02.jpg", 
            title : "Robe Bazin", 
            desc :"Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.            ",
            price : "100", 
            id_cat:1,
        },{
            id : 360742, 
            img : "https://www.awalebiz.com/images/detailed/15/Kurta_Kya_02.jpg", 
            title : "Ensemble Boubou", 
            alt : "Robe",
            price : "100", 
            id_cat:1,
        },
        {
            id : 5, 
            img : "https://www.awalebiz.com/images/detailed/15/Tunique_Aida_02.jpg", 
            title : "Robe Bazin", 
            desc :"Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.            ",
            price : "100", 
            id_cat:1,
        },
        {
            id : 406364, 
            img : "https://www.awalebiz.com/images/detailed/15/Kiba_Guigui_02.jpg", 
            title : "Ensemble Boubou", 
            desc :"Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.            ",
            price : "100", 
            id_cat:1,
        },
        {
            id : 423762, 
            img : "https://i.etsystatic.com/16803487/r/il/79efce/3112793100/il_570xN.3112793100_9172.jpg", 
            title : "Robe femme Bazin riche", 
            desc :"Robe bazin riche pour femmes africaines Getzner de première classe bazin Vêtements bazin africains pour femmes",
            price : "350", 
            id_cat:1,
        },
        {
            id : 736642, 
            img : "https://i.etsystatic.com/16803487/r/il/645f49/4202509745/il_794xN.4202509745_209l.jpg", 
            title : "Robe bazin riche", 
            desc :"Robe bazin riche pour femmes africaines Getzner de première classe bazin Vêtements bazin africains pour femmes",
            price : "350", 
            id_cat:1,
        },
        {
            id : 530658, 
            img : "https://i.etsystatic.com/16803487/r/il/f45e99/4202518975/il_794xN.4202518975_ro6t.jpg", 
            title : "Robe bazin riche ", 
            desc :"Robe bazin riche pour femmes africaines Getzner de première classe bazin Vêtements bazin africains pour femmes",
            price : "350", 
            id_cat:1,
        },
        
    ]

    },
    //Femme Chaussures
    {
    id:2,
    category:"femme",
    sousCategory:"chaussures",
    products:[
        
        {  id : 766813, 
            img : "https://cdn.fashiola.fr/L745121157/saint-laurent-sandales-opyum-85-en-cuir-verni.jpg", 
            title : "Yves Saint Laurent Sandales Opyum 85 en cuir verni            ", 
            desc: "Une allure raffinée et moderne se doit de reposer sur des bases solides, ce que vous donneront les sandales Opyum de Saint Laurent, nommées en l’honneur du parfum éponyme de la maison. Saint Laurent Sandales Opyum 85 en cuir verni",
            price : "50", 
               id_cat:2,
          },
        {  id : 273973, 
            img : "https://cdn.fashiola.fr/L741495672/saint-laurent-femme-sandales-sandales-cassandra-en-cuir.jpg", 
            title : "Yves Saint Laurent Sandales Cassandra en cuir", 
            desc: "Sandales Cassandra en cuir. Saint Laurent Sandales Cassandra en cuir            ",
            price : "50", 
               id_cat:2,
          },
        {  id : 515956, 
            img : "https://cdn.fashiola.fr/L745053661/saint-laurent-sandales-cassandra-en-daim.jpg", 
            title : "Sandales Cassandra en daim ", 
            desc: "La ligne Cassandra de Saint Laurent s’agrandit pour accueillir ces sandales plates. Saint Laurent Sandales Cassandra en daim",
            price : "30", 
               id_cat:2,
          },
        {  id : 494565, 
            img : "https://cdn.fashiola.fr/L740033047/saint-laurent-sandales-bea-en-cuir-verni.jpg", 
            title : "Sandales Bea en cuir verni", 
            desc: "Conçues en cuir verni, les sandales Bea de Saint Laurent présentent une bride de cheville fine à boucle. Saint Laurent Sandales Bea en cuir verni",
            price : "50", 
               id_cat:2,
          },
        {  id : 790460, 
            img : "https://cdn.fashiola.fr/L745021984/blancheporte-femme-a-talons-sandales-a-talon-dessus-croise.jpg", 
            title : "Sandales À Talon Dessus Croisé", 
            desc: "Dimensions : - Talon 8 cm environ Composition : - Dessus : textile suédine - Doublure : synthétique - Semelle intérieure : cuir - Semelle extérieure : élastomère Description : - Textile doux, aspect suédine - Semelle intérieure en cuir véritable pour un meilleur confort - Fine bride cheville avec élastiques d’aisance - Ajustable par boucle et ardillon en métal argenté",
            price : "50", 
               id_cat:2,
          },
        {  id : 491362, 
            img : "https://cdn.fashiola.fr/L658877335/nike-baskets-challenger-og.jpg", 
            title : "Basket Nike", 
            desc: "Dessus en cuir et synthétique. Fermeture frontale à lacets. Détails logo. Semelle en caoutchouc",
            price : "50", 
               id_cat:2,
          },
        {  id : 410337, 
            img : "https://cdn.fashiola.fr/L666656666/adidas-baskets-en-daim-w-gazelle.jpg", 
            title : "adidas Baskets En Daim", 
            desc: "Dessus en daim. Fermeture frontale à lacets. Détails logo. Détails de couleur contrastante. Semelle en caoutchouc     ",
            price : "50", 
               id_cat:2,
          },
        {  id : 363155, 
            img : "https://cdn.fashiola.fr/L577562041/gucci-baskets-supreme-gg-ace-en-toile-imprimee.jpg", 
            title : "Gucci Baskets Suprême GG Ace en toile imprimée", 
            desc: "Imaginées à grand renfort d'éléments signature tels que le motif GG, ici rehaussé de luxueuses abeilles dorées, ou encore la bande Web, en écho aux contreforts en cuir métallisé embossé façon peau de serpent rouge d'un côté et verte de l'autre, les baskets Suprême GG Ace sont naturellement signées Gucci. Gucci Baskets Suprême GG Ace en toile imprimée            ",
            price : "50", 
               id_cat:2,
          },
         
    ]

    },

    //Femme Sacs
    
    {
    id:3,
    category:"femme",
    sousCategory:"sacs",
    products:[
        
        {  id : 831379, 
            img : "https://www.awalebiz.com/images/detailed/13/35YP9PFK-large.jpg", 
            title : "HERMES INSPIRED", 
            desc: "Sac à main femme super pratique pour le travail ou les sorties Matières: cuir lisse et pagne tissé Dimensions: 31 x 24 x 14 cm",
            price : "50", 
               id_cat:3,
          },
        {  id : 988482, 
            img : "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-sac-neverfull-mm-toile-monogram-sacs-%C3%A0-main--M40995_PM2_Front%20view.png?wid=656&hei=656", 
            title : "Louis Vuitton NeverFull", 
            desc: "Ce cabas Neverfull MM séduit grâce à des lignes intemporelles et des éléments emblématiques. Confectionné en toile Monogram souple avec une garniture en cuir de vache naturel, il offre une grande capacité de rangement sans être volumineux. Les lacets sur le côté peuvent être resserrés ou desserrés pour varier les styles. Les poignées fines et confortables du sac permettent de le porter à l’épaule ou sur le bras. Le modèle doublé en textile coloré comporte une pochette amovible à utiliser séparément ou comme une poche supplémentaire.",
            price : "60", 
               id_cat:3,
          },
        {  id : 867654, 
            img : "https://cdn.fashiola.fr/L745679758/louis-vuitton-sac-a-main-alma-en-cuir.jpg", 
            title : "Louis Vuitton Alma en cuir", 
            desc: "Sac à main Alma en cuir",
            price : "50", 
               id_cat:3,
          },
        {  id : 322651, 
            img : "https://cdn.fashiola.fr/L744681359/saint-laurent-femme-pochettes-etuis-pochette-en-cuir-embosse-monogramme.jpg", 
            title : "Yves Saint Laurent Pochette En Cuir Embossé Monogramme", 
            desc: "Hauteur : 16 cm Largeur : 21 cm Profondeur : 3 cm. Dragonne amovible en cuir. Rabat frontal avec fermeture à bouton-pression. Logo frontal en métal doré",
            price : "50", 
               id_cat:3,
          },
        {  id : 150735, 
            img : "https://cdn.fashiola.fr/L746155039/tommy-hilfiger-sac-cabas-poppy.jpg", 
            title : "Tommy Hilfiger Sac cabas Poppy Bleu            ", 
            desc: "Sac cabas Poppy",
            price : "50", 
               id_cat:3,
          },
        {  id : 350758, 
            img : "https://cdn.fashiola.fr/L745222802/saint-laurent-sac-loulou-medium-en-daim.jpg", 
            title : "Saint Laurent Loulou Medium en daim", 
            desc: "Apportez une petite touche de chic typiquement parisien à vos tenues avec l’un des sacs les plus emblématiques de Saint Laurent, le Loulou Medium, ici présenté en taupe. Saint Laurent Sac Loulou Medium en daim",
            price : "50", 
               id_cat:3,
          },
        {  id : 350758, 
            img : "https://cdn.fashiola.fr/L729456559/saint-laurent-sac-sunset-monogram-medium-en-cuir.jpg", 
            title : "Sac Sunset Monogram Medium en cuir            ", 
            desc: "Ajoutez un modèle classique à votre vestiaire avec le sac Sunset Monogram Medium de Saint Laurent. Saint Laurent Sac Sunset Monogram Medium en cuir",
            price : "50", 
               id_cat:3,
          },
        {  id : 594850, 
            img : "https://cdn.fashiola.fr/L744589326/louis-vuitton-femme-sacs-valises-femme-bagages-leather.jpg", 
            title : "Femme Bagages Leather", 
            desc: "Sac fourre-tout Louis Vuitton 90s Keepall 50 cm en toile imprimée monogramme classique. Double anse en cuir et détails marron clair. Fermeture zippée dorée avec double tirette.",
            price : "60", 
               id_cat:3,
          },

    ]

    },

    //Femme Accessoires
    
    {
    id:4,
    category:"femme",
    sousCategory:"accessoires",
    products:[
        
        {  id : 901520, 
            img : "https://www.cdiscount.com/pdt2/5/2/1/1/700x700/auc4770344166521/rw/bijoux-marocain-faits-a-la-main-en-cristal-access.jpg", 
            title : "Bijoux marocain faits à la main en cristal", 
            desc : "Bijoux marocain faits à la main en cristal",
            price : "40", 
               id_cat:4,
        
          },
          {  id : 959046, 
            img : "https://i.pinimg.com/originals/a9/68/45/a968450c891a478403a07632559fc59c.jpg", 
            title : "Bijoux ", 
            desc : "Bijoux",
            price : "40", 
               id_cat:4,
          },
          {  id : 732793, 
            img : "https://www.cdiscount.com/pdt2/6/8/3/1/700x700/ofe3167889548683/rw/ofeli-r-bijoux-africaines-parures-femmes-cristal-d.jpg", 
            title : "Bijoux africaines Parures Femmes", 
            desc : "Bijoux africaines Parures Femmes Cristal de Fête de Vacances Accessoires",
            price : "40", 
               id_cat:4,
          },
    ]

    },
    

  //Homme Vetements
   
  {
    id:5,
    category:"homme",
    sousCategory:"vetements",
    products:[
        
        {  id : 492428, 
            img : "https://adopteunboubou.com/wp-content/uploads/2021/11/c6b364d4-19cb-408b-9c19-11e9716c99c8.jpg", 
            title : "Ensemble Homme", 
            desc : "Cette tenue élégante est faite à la main et conçue avec des matières naturelles de haute qualité. Il convient à toutes sortes d’occasions et est livré avec un pantalon assorti avec un cordon de serrage pour plus de facilité.",
            price : "80", 
               id_cat:5,
        
          },
          {  id : 592125, 
            img : "https://i0.wp.com/www.ehtymag.com/wp-content/uploads/2022/02/boubou-africain-homme-ehtymag-ref-5.jpeg?resize=768%2C768&ssl=1", 
            title : "Ensemble Homme", 
            desc : "Prestance et élégance sont les maîtres mots qui caractérisent cet ensemble. Ils témoignent d'un homme à la personnalité forte, qui affirme son identité et sa culture sans compromis.",
            price : "80", 
               id_cat:5,

          },
          {  id : 774823, 
            img : "https://d17a17kld06uk8.cloudfront.net/products/6MR11RA/E44TV6BI-original.jpg", 
            title : "Ensemble Homme", 
            desc : "Le Kiba est une fusion des charmes de la veste et de ceux du boubou traditionnel africain. Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donnent une allure spécifique de costume africain",
            price : "80", 
               id_cat:5,
          },
          {  id : 830816, 
            img : "https://d17a17kld06uk8.cloudfront.net/products/78NHEL6/EDB4NZEL-original.jpg", 
            title : "Ensemble Homme", 
            desc : "Craie rayures hommes africains costume, vêtements pour hommes africains, vêtements africains, hommes africains de mariage",
            price : "80", 
               id_cat:5,
          },
          {  id : 994766, 
            img : "https://d17a17kld06uk8.cloudfront.net/products/4HR658Z/A7IJ1KAV-large.webp", 
            title : "Costume homme 3 pièces", 
            desc : "Costume homme 3 pièces",
            price : "250", 
               id_cat:5,
          },
          {  id : 239638, 
            img : "https://d17a17kld06uk8.cloudfront.net/products/NCEURI8/A1FUIZ1Y-large.webp", 
            title : "Costume pour homme", 
            desc : "Costume pour homme",
            price : "250", 
               id_cat:5,
          },
          {  id : 581577, 
            img : "https://d17a17kld06uk8.cloudfront.net/products/9UCZYRS/DQHUDIJK-large.webp", 
            title : "Costume ajusté smoking trois pièces pour hommes", 
            desc : "Costume ajusté smoking trois pièces pour hommes",
            price : "250", 
               id_cat:5,
          },
          {  id : 726810, 
            img : "https://d17a17kld06uk8.cloudfront.net/products/7NJ8V7Z/33FUCJ7T-large.webp", 
            title : "Smoking bleu marine brodé fleuri", 
            desc : "Smoking bleu marine brodé fleuri",
            price : "250", 
               id_cat:5,
          },
          {  id : 790548, 
            img : "https://d17a17kld06uk8.cloudfront.net/products/HHA62YW/IX8JZQT5-large.webp", 
            title : "Hommes costume", 
            desc : "Hommes costume",
            price : "250", 
               id_cat:5,
          },
    ]

    },

    //Homme Chaussure
  {
    id:6,
    category:"homme",
    sousCategory:"chaussures",
    products:[
        
        {  id : 281184, 
            img : "https://www.loding.fr/4991-home_default_2x/bottines-chelsea-noir-cuir-veau-pleine-fleur.jpg", 
            title : "CHELSEA BOOTS NUSCO 362            ", 
            desc : "CHELSEA BOOTS NUSCO 362 ",
            price : "150", 
               id_cat:6,
        
          },
          {  id : 356082, 
            img : "https://www.loding.fr/tun/5295-home_default/straight-toe-cap-derby-leather-box.jpg", 
            title : "DERBY ORANI 392            ", 
            desc : "DERBY ORANI 392            ",
            price : "150", 
               id_cat:6,

          },
          {  id : 642190, 
            img : "https://www.loding.fr/tun/5150-big_default/brown-suede-chukka-boots-for-men.jpg", 
            title : "SUEDE CHUKKA BOOTS OSILO 374", 
            desc : "SUEDE CHUKKA BOOTS OSILO 374",
            price : "150", 
               id_cat:6,
          },
          {  id : 355363, 
            img : "https://www.loding.fr/tun/5021-big_default/suede-desert-boots.jpg", 
            title : "DESERT BOOTS FIRMO 393 SUEDE", 
            desc : "DESERT BOOTS FIRMO 393 SUEDE",
            price : "150", 
               id_cat:6,
          },
          {  id : 562402, 
            img : "https://www.loding.fr/tun/5111-big_default/suede-leather-tassel-loafer-for-men.jpg", 
            title : "TASSEL LOAFER MELIA 396 SUEDE LEATHER", 
            desc : "TASSEL LOAFER MELIA 396 SUEDE LEATHER",
            price : "80", 
               id_cat:6,
          },
          {  id : 562401, 
            img : "https://www.loding.fr/tun/27-big_default/brown-suede-penny-loafer-sulky-300.jpg", 
            title : "PENNY LOAFERS SULKY 300 SUEDE", 
            desc : "PENNY LOAFERS SULKY 300 SUEDE",
            price : "80", 
               id_cat:6,
          },
          {  id : 562301, 
            img : "https://www.loding.fr/tun/2062-big_default/pure-leather-penny-loafer-goodyear-welted-sulky-300.jpg", 
            title : "PENNY LOAFERS SULKY 300", 
            desc : "PENNY LOAFERS SULKY 300",
            price : "80", 
               id_cat:6,
          },
          {  id : 561301, 
            img : "https://www.loding.fr/tun/2812-big_default/richelieu-nevisa-351-suede.jpg", 
            title : "STRAIGHT TOE-CAP OXFORD NEVISA 351 SUEDE", 
            desc : "STRAIGHT TOE-CAP OXFORD NEVISA 351 SUEDE",
            price : "150", 
               id_cat:6,
          },
          {  id : 561201, 
            img : "https://www.loding.fr/tun/4505-big_default/blue-oxford-shoes-with-perforated-stiches.jpg", 
            title : "OXFORD SHOES WITH PERFORATED STICHES ISEO 386", 
            desc : "OXFORD SHOES WITH PERFORATED STICHES ISEO 386",
            price : "150", 
               id_cat:6,
          },
          {  id : 551201, 
            img : "https://www.loding.fr/tun/5041-big_default/suede-leather-tassel-loafer-for-men.jpg", 
            title : "TASSEL LOAFER MELIA 397 SUEDE LEATHER", 
            desc : "TASSEL LOAFER MELIA 397 SUEDE LEATHER",
            price : "80", 
               id_cat:6,
          },
          {  id : 541201, 
            img : "https://www.loding.fr/tun/5268-big_default/suede-leather-espadrilles-loafer-for-men.jpg", 
            title : "ESPADRILLES LOAFER CAPRI 1100 SUEDE LEATHER", 
            desc : "ESPADRILLES LOAFER CAPRI 1100 SUEDE LEATHER",
            price : "80", 
               id_cat:6,
          },
          {  id : 531201, 
            img : "https://www.loding.fr/tun/2484-big_default/single-monk-shoes-taylor-502.jpg", 
            title : "SINGLE MONK NEW TAYLOR 502", 
            desc : "SINGLE MONK NEW TAYLOR 502",
            price : "150", 
               id_cat:6,
          },
          {  id : 521201, 
            img : "https://www.loding.fr/tun/2434-big_default/suede-double-monk-shoes.jpg", 
            title : "SUEDE MONK MELLERAY 473", 
            desc : "SUEDE MONK MELLERAY 473",
            price : "150", 
               id_cat:6,
          },
          {  id : 421201, 
            img : "https://www.loding.fr/tun/195-big_default/monk-shoes-melleray-box-calf.jpg", 
            title : "MONK MELLERAY 473", 
            desc : "MONK MELLERAY 473",
            price : "150", 
               id_cat:6,
          },
          {  id : 421211, 
            img : "https://megadeals237.com/wp-content/uploads/2020/05/babouche-homme-ep-a-bandes-croisees-en-cuir-1.jpg", 
            title : "Babouche Homme", 
            desc : "Babouche Homme",
            price : "30", 
               id_cat:6,
          },
          {  id : 321211, 
            img : "https://cdn.artisanat-shop.com/pub/media/catalog/product/cache/10e72dd1484abef8d7982487e727ecbb/b/a/babouche_0007_ALIBABA.jpg", 
            title : "Babouche en cuir Homme", 
            desc : "Babouche en cuir Homme",
            price : "30", 
               id_cat:6,
          },
          {  id : 721211, 
            img : "https://megadeals237.com/wp-content/uploads/2020/05/babouche-homme-po-a-bande-tisse-en-cuir-2-1.jpg", 
            title : "Babouche en cuir a bande tissé Homme", 
            desc : "Dotez vous d'une élégance sans pareille avec vos babouches cuir a bande tissé",
            price : "30", 
               id_cat:6,
          },
    ]

    },
    //Homme Accessoires
  {
    id:7,
    category:"homme",
    sousCategory:"accessoires",
    products:[
        
          {  id : 124792, 
            img : "https://www.leguidedesmontres.com/_files/references/images/856_899_hermes__036929ww00.jpg", 
            title : "Montre HERMÈS HOMME", 
            desc : "Montre HERMÈS HOMME",
            price : "150", 
               id_cat:7,
          },
          {  id : 124782, 
            img : "https://www.leguidedesmontres.com/_files/references/images/1201_1298_hublot__311.ci.1170.gr.jpg", 
            title : "Montre HUBLOT HOMME", 
            desc : "Montre HUBLOT HOMME",
            price : "100", 
               id_cat:7,
          },
          {  id : 124772, 
            img : "https://assets.hermes.com/is/image/hermesproduct/montre-heure-h-petit-modele-25mm--036721WW00-front-1-300-0-1000-1000_b.jpg", 
            title : "Montre HERMÈS HOMME", 
            desc : "Montre HERMÈS HOMME",
            price : "150", 
               id_cat:7,
          },
          {  id : 124672, 
            img : "https://cdn.lepage.fr/9418-home_default/montre-hublot-big-bang-gold-gold-cadran-noir-mat-bracelet-caoutchouc-noir-44-mm.jpg", 
            title : "Montre Hublot Big Bang Gold Gold cadran noir mat bracelet caoutchouc noir 44 mm", 
            desc : "Montre Hublot Big Bang Gold Gold cadran noir mat bracelet caoutchouc noir 44 mm",
            price : "100", 
               id_cat:7,
          },
          {  id : 124662, 
            img : "https://content.rolex.com/dam/2022/upright-bba-with-shadow/m126233-0039.png?impolicy=v6-upright&imwidth=270", 
            title : "Montre Rolex Homme", 
            desc : "Montre Rolex Homme",
            price : "150", 
               id_cat:7,
          },
          {  id : 124652, 
            img : "https://cdn2.chrono24.com/images/uhren/23746903-4bjrcv65jzdl89hescw1hf53-ExtraLarge.jpg", 
            title : "Montre Rolex bicolores Homme", 
            desc : "Montre Rolex bicolores Homme",
            price : "150", 
               id_cat:7,
          },
          {  id : 124552, 
            img : "https://www.my-watchsite.fr/31461-home_default/santos-de-cartier-chronographe.jpg", 
            title : "Montre Cartier  Homme", 
            desc : "Montre Cartier  Homme",
            price : "150", 
               id_cat:7,
          },
    ]

    },
//Enfant Vetements
{
    id:8,
    category:"enfant",
    sousCategory:"vetements",
    products:[
        
        {  id : 420282, 
            img : "https://www.modeafricaine.com/wp-content/uploads/2021/05/3E16514D-7E33-44ED-AA21-26C92066D28C.jpeg", 
            title : "ENSEMBLE DASHIKI", 
            desc : "ENSEMBLE DASHIKI",
            price : "50", 
               id_cat:8,
        
          },
          {  id : 297996, 
            img : "https://d17a17kld06uk8.cloudfront.net/products/DB6TX7Z/8Y45M12R-default.jpg", 
            title : "Ensemble Garçon", 
            desc : "Ensemble Garçon",
            price : "50", 
               id_cat:8,

          },
          {  id : 769128, 
            img : "https://i.pinimg.com/236x/c0/34/77/c034778f80cdb7d2793f4275e913b8e0.jpg", 
            title : "Ensemble Garçon", 
            desc : "Ensemble Garçon",
            price : "50", 
               id_cat:8,
          },
          {  id : 531885, 
            img : "https://static.wixstatic.com/media/9637da_b3ee3d6818c64daca09d830485b39fdb~mv2.jpg/v1/fill/w_800,h_800,al_c,q_85/9637da_b3ee3d6818c64daca09d830485b39fdb~mv2.jpg", 
            title : "Ensemble Bazin pour fille", 
            desc : "Ensemble Bazin pour fille",
            price : "50", 
               id_cat:8,
          },
    ]

    },
//Enfants Chaussures

{
    id:9,
    category:"enfant",
    sousCategory:"chaussures",
    products:[
        
        {  id : 759245, 
            img : "https://contents.mediadecathlon.com/p2185458/k5ced3c6e6505f6d8f16100d30f61f492/chaussures-enfant-100-i-learn-rose-du-20-au-24.jpg?&f=800x800", 
            title : "Chaussure Enfant", 
            desc : "Chaussure Enfant",
            price : "0", 
               id_cat:9,
        
          },
          {  id : 260313, 
            img : "https://cdn.sarenza.cloud/_img/productsv4/0000227022/0000227022_426516_09_504x690.jpg?201912161045&v=20180830155342", 
            title : "Chaussure pour fille", 
            desc : "Chaussure pour fille",
            price : "40", 
               id_cat:9,

          },
          {  id : 499927, 
            img : "https://cdn.sarenza.cloud/_img/productsv4/0000258881/0000258881_478110_09_504x690.jpg?202009210945&v=20180830155342", 
            title : "Chaussure Gris", 
            desc : "Chaussure Gris",
            price : "40", 
               id_cat:9,
          },
          {  id : 476238, 
            img : "https://www.cdiscount.com/pdt2/9/6/3/1/700x700/mp04855963/rw/chaussure-enfant-2017-nouvelle-arrivee-confortable.jpg", 
            title : "Chaussure mixte pour enfant", 
            desc : "Chaussure mixte pour enfant",
            price : "40", 
               id_cat:9,
          },
    ]

    },

//Enfants Accessoires
{
    id:10,
    category:"enfant",
    sousCategory:"accessoires",
    products:[
        
        {  id : 237345, 
            img : "https://cdn.shopify.com/s/files/1/0567/5529/0250/products/Boubou-Africain-Femme-Mariage_600x.jpg?v=1644256505", 
            title : "R o b e", 
            alt : "Robe",
            price : "40", 
               id_cat:10,
        
          },
          {  id : 489506, 
            img : "https://cdn.shopify.com/s/files/1/0567/5529/0250/products/Boubou-Africain-Femme-Mariage_600x.jpg?v=1644256505", 
            title : "R o b e", 
            alt : "Robe",
            price : "40", 
               id_cat:10,

          },
          {  id : 990818, 
            img : "https://cdn.shopify.com/s/files/1/0567/5529/0250/products/Boubou-Africain-Femme-Mariage_600x.jpg?v=1644256505", 
            title : "R o b e", 
            alt : "Robe",
            price : "40", 
               id_cat:10,
          },
          {  id : 490818, 
            img : "https://cdn.shopify.com/s/files/1/0567/5529/0250/products/Boubou-Africain-Femme-Mariage_600x.jpg?v=1644256505", 
            title : "R o b e", 
            alt : "Robe",
            price : "40", 
               id_cat:10,
          },
    ]

    },

    //Boubou Category
{
    id:11,
    category:"Boubou",
    products:[
      {
        id : 290067, 
        img : "https://www.awalebiz.com/images/detailed/16/24de75049a187274e7280ed060978978_m7wl-2t.jpg", 
        title : "Ensemble Boubou Homme    ",
        desc : "Ensemble tradimoderne avec broderie dorée.    ", 
        price : "80",
           id_cat:11,
      
        },
        
      {  id : 746950, 
        img : "https://www.awalebiz.com/images/detailed/15/Kiba_Yusuf_02.jpg", 
        title : "Ensemble Boubou  Homme  ", 
        desc : "Ensemble tradi moderne homme.    ",
        price : "80", 
           id_cat:11,
      },
      
      {  id : 765039, 
        img : "https://www.awalebiz.com/images/detailed/15/Kiba_Guigui_02.jpg", 
        title : "Ensemble Boubou Femme", 
        desc : "Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.",
        price : "80", 
           id_cat:11,
      },
      
      {  id : 332215, 
        img : "https://www.awalebiz.com/images/detailed/15/Kiba_Tima_03.jpg", 
        title : "Ensemble Boubou Femme", 
        desc : "Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.",
        price : "80", 
           id_cat:11,
      },
    ]

    },

    //voir plus boubu
    {
    id:12,
    categoryV:"Boubou",
    products:[
      {
        id : 290067, 
        img : "https://www.awalebiz.com/images/detailed/16/24de75049a187274e7280ed060978978_m7wl-2t.jpg", 
        title : "Ensemble Boubou Homme    ",
        desc : "Ensemble tradimoderne avec broderie dorée.    ", 
        price : "80",
           id_cat:12,
      
        },
        
      {  id : 746950, 
        img : "https://www.awalebiz.com/images/detailed/15/Kiba_Yusuf_02.jpg", 
        title : "Ensemble Boubou  Homme  ", 
        desc : "Ensemble tradi moderne homme.    ",
        price : "80", 
           id_cat:12,
      },
      
      {  id : 765039, 
        img : "https://www.awalebiz.com/images/detailed/15/Kiba_Guigui_02.jpg", 
        title : "Ensemble Boubou Femme", 
        desc : "Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.",
        price : "80", 
           id_cat:12,
      },
      
      {  id : 332215, 
        img : "https://www.awalebiz.com/images/detailed/15/Kiba_Tima_03.jpg", 
        title : "Ensemble Boubou Femme", 
        desc : "Il intègre des épaulettes soigneusement étudiées, des manches veste raffinées ainsi que des attributs propres à l’habit africain, ce qui lui donne une allure spécifique de costume africain.",
        price : "80", 
           id_cat:12,
      },
    ]

    },
//chemise Category

{
  id:13,
  category:"Chemises",
  products:[
    {
      id : 919854, 
      img : "https://www.cdiscount.com/pdt2/1/4/2/1/700x700/mp20945142/rw/chemise-fashion-pour-homme-chemise.jpg", 
      title : "Chemise Fashion Pour Homme",
      desc : "Chemise Fashion Pour Homme", 
      price : "40",
         id_cat:13,
    
      },
      
    {  id : 387254, 
      img : "https://www.cdiscount.com/pdt2/1/8/0/1/550x550/mp53345180/rw/homme-chemises-en-flanelle-chemises-a-carreaux-a-m.jpg", 
      title : "Homme Chemises en Flanelle", 
      desc : "Chemises à Carreaux à Manche Longue",
      price : "35", 
         id_cat:13,
    },
    
    {  id : 389718, 
      img : "https://www.cdiscount.com/pdt2/0/2/8/1/700x700/mp56463028/rw/nouveaux-hommes-chemise-decontractee-en-flanelle-a.jpg", 
      title : "chemise décontractée en flanelle", 
      desc : "chemise chaud homme vêtements flanelle chemise à carreaux hommes grande taille",
      price : "40", 
         id_cat:13,
    },
    
    {  id : 361500, 
      img : "https://www.cdiscount.com/pdt2/1/0/0/1/700x700/mp58328100/rw/chemise-chemisette-chemisechemise-imprimee-papil.jpg", 
      title : "Chemise Imprimée Papillon en Coton", 
      desc : "Chemise Imprimée Papillon pour Hommes en Coton, Vêtement Cintré à Manches Longues",
      price : "40", 
         id_cat:13,
    },
  ]
}, 

//voir plus chemise
{
  id:14,
  categoryV:"Chemises",
  products:[
    {
      id : 919854, 
      img : "https://www.cdiscount.com/pdt2/1/4/2/1/700x700/mp20945142/rw/chemise-fashion-pour-homme-chemise.jpg", 
      title : "Chemise Fashion Pour Homme",
      desc : "Chemise Fashion Pour Homme", 
      price : "40",
         id_cat:14,
    
      },
      
    {  id : 387254, 
      img : "https://www.cdiscount.com/pdt2/1/8/0/1/550x550/mp53345180/rw/homme-chemises-en-flanelle-chemises-a-carreaux-a-m.jpg", 
      title : "Homme Chemises en Flanelle", 
      desc : "Chemises à Carreaux à Manche Longue",
      price : "35", 
         id_cat:14,
    },
    
    {  id : 389718, 
      img : "https://www.cdiscount.com/pdt2/0/2/8/1/700x700/mp56463028/rw/nouveaux-hommes-chemise-decontractee-en-flanelle-a.jpg", 
      title : "chemise décontractée en flanelle", 
      desc : "chemise chaud homme vêtements flanelle chemise à carreaux hommes grande taille",
      price : "40", 
         id_cat:14,
    },
    
    {  id : 361500, 
      img : "https://www.cdiscount.com/pdt2/1/0/0/1/700x700/mp58328100/rw/chemise-chemisette-chemisechemise-imprimee-papil.jpg", 
      title : "Chemise Imprimée Papillon en Coton", 
      desc : "Chemise Imprimée Papillon pour Hommes en Coton, Vêtement Cintré à Manches Longues",
      price : "40", 
         id_cat:14,
    },
  ]
}, 

//Robes 

{
  id:15,
  category:"Robes",
  products:[
    {
      id : 880446, 
      img : "https://i.etsystatic.com/16803487/r/il/ad0614/3160515691/il_794xN.3160515691_oq8f.jpg", 
      title : "Robe Bazin Riche",
      desc : "", 
      price : "350",
         id_cat:15,
    
      },
      
    {  id : 891868, 
      img : "https://i.etsystatic.com/16803487/r/il/8b6a75/4135232728/il_794xN.4135232728_mlr7.jpg", 
      title : "Robe Bazin Riche", 
      desc : "Robe Blanche avec broderie Bazin Riche ",
      price : "350", 
         id_cat:15,
    },
    
    {  id : 867212, 
      img : "https://i.etsystatic.com/16803487/r/il/96159b/4182887851/il_794xN.4182887851_g23p.jpg", 
      title : "Robe Bazin Riche", 
      desc : "Robe Bazin Riche",
      price : "350", 
         id_cat:15,
    },
    
    {  id : 519910, 
      img : "https://i.etsystatic.com/16803487/r/il/b9c504/3160500881/il_794xN.3160500881_646p.jpg", 
      title : "Robe femme Bazin riche", 
      desc : "Robe femme Bazin riche",
      price : "350", 
         id_cat:15,
    },
  ]
}, 

//voirPlus Robes
{
  id:16,
  categoryV:"Robes",
  products:[
    {
      id : 880446, 
      img : "https://i.etsystatic.com/16803487/r/il/ad0614/3160515691/il_794xN.3160515691_oq8f.jpg", 
      title : "Robe Bazin Riche",
      desc : "", 
      price : "350",
         id_cat:16,
    
      },
      
    {  id : 891868, 
      img : "https://i.etsystatic.com/16803487/r/il/8b6a75/4135232728/il_794xN.4135232728_mlr7.jpg", 
      title : "Robe Bazin Riche", 
      desc : "Robe Blanche avec broderie Bazin Riche ",
      price : "350", 
         id_cat:16,
    },
    
    {  id : 867212, 
      img : "https://i.etsystatic.com/16803487/r/il/96159b/4182887851/il_794xN.4182887851_g23p.jpg", 
      title : "Robe Bazin Riche", 
      desc : "Robe Bazin Riche",
      price : "350", 
         id_cat:16,
    },
    
    {  id : 519910, 
      img : "https://i.etsystatic.com/16803487/r/il/b9c504/3160500881/il_794xN.3160500881_646p.jpg", 
      title : "Robe femme Bazin riche", 
      desc : "Robe femme Bazin riche",
      price : "350", 
         id_cat:16,
    },
  ]
}, 

//Chaussures

{
  id:17,
  category :"chaussures", 
  sousCategory:"chaussures",
  products:[
    {
      id : 908050, 
      img : "https://photos6.spartoo.com/photos/211/21134924/21134924_350_A.jpg", 
      title : "Sandale Femme",
      desc : "", 
      price : "30",
         id_cat:17,
    
      },
      
    {  id : 897510, 
      img : "https://www.pimkie.fr/dw/image/v2/AAYN_PRD/on/demandware.static/-/Sites-pimkie-master-catalog/default/dwa6878e83/images/916782_899A08_portrait_HD_1.JPG?sw=760&sh=938", 
      title : "Talon", 
      desc : "Talon Noir",
      price : "50", 
         id_cat:17,
    },
    
    {  id : 810690, 
      img : "https://www.loding.fr/5078-home_default_2x/chaussures-richelieu-brogue-bout-fleuri-317-soleto.jpg", 
      title : "Chaussure pour Homme", 
      desc : "",
      price : "150", 
         id_cat:17,
    },
    
    {  id : 120135, 
      img : "https://megadeals237.com/wp-content/uploads/2020/05/babouche-homme-po-a-bande-tisse-en-cuir-2-1.jpg", 
      title : "Babouche pour Homme", 
      desc : "Babouche pour Homme",
      price : "30", 
         id_cat:17,
    },
  ]
}, 

//voirPlus Chaussures
{
  id:17,
  categoryV :"chaussures", 
  sousCategory:"chaussures",
  products:[
    {
      id : 908050, 
      img : "https://photos6.spartoo.com/photos/211/21134924/21134924_350_A.jpg", 
      title : "Sandale Femme",
      desc : "", 
      price : "30",
         id_cat:17,
    
      },
      
    {  id : 897510, 
      img : "https://www.pimkie.fr/dw/image/v2/AAYN_PRD/on/demandware.static/-/Sites-pimkie-master-catalog/default/dwa6878e83/images/916782_899A08_portrait_HD_1.JPG?sw=760&sh=938", 
      title : "Talon", 
      desc : "Talon Noir",
      price : "50", 
         id_cat:17,
    },
    
    {  id : 810690, 
      img : "https://www.loding.fr/5078-home_default_2x/chaussures-richelieu-brogue-bout-fleuri-317-soleto.jpg", 
      title : "Chaussure pour Homme", 
      desc : "",
      price : "150", 
         id_cat:17,
    },
    
    {  id : 120135, 
      img : "https://megadeals237.com/wp-content/uploads/2020/05/babouche-homme-po-a-bande-tisse-en-cuir-2-1.jpg", 
      title : "Babouche pour Homme", 
      desc : "Babouche pour Homme",
      price : "30", 
         id_cat:17,
    },
  ]
}, 
]

export default ApiCategoryShower